import React from 'react';
import { router } from '@inertiajs/react';
import {
  Package,
  CheckCircle2,
  Banknote,
  Clock,
  AlertTriangle,
  RotateCcw,
  XCircle,
  Share2,
  Building2
} from 'lucide-react';
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  Legend
} from 'recharts';
import { ToggleGroup } from '@/components/ui/toggle-group';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

interface ReportsProps {
  period: string;
  metrics: {
    received: number;
    collected: number;
    revenueFormatted: string;
    waiting: number;
    overdue: number;
    avgPickupTime: string;
    returned: number;
    cancelled: number;
  };
  trendData: {
    date: string;
    received_count: number;
    collected_count: number;
  }[];
  pickupPointComparison: {
    id: number;
    name: string;
    park: string;
    received: number;
    collected: number;
    revenue: string;
    collectionRate: number;
  }[];
}

export default function Reports({
  period,
  metrics,
  trendData,
  pickupPointComparison,
}: ReportsProps) {
  const handlePeriodChange = (newPeriod: string) => {
    router.get('/admin/reports', { period: newPeriod }, { preserveState: true, preserveScroll: true });
  };

  const periodOptions = [
    { value: 'today', label: 'Today' },
    { value: 'week', label: 'This Week' },
    { value: '7d', label: 'Last 7 Days' },
    { value: '30d', label: 'Last 30 Days' },
  ];

  const handleShareWhatsApp = () => {
    const text = `*ParkDrop Summary Report (${periodOptions.find(p => p.value === period)?.label})*\n\n` +
      `📦 Packages Received: ${metrics.received}\n` +
      `✅ Packages Collected: ${metrics.collected}\n` +
      `💰 Revenue Collected: ${metrics.revenueFormatted}\n` +
      `⏱️ Average Pickup Time: ${metrics.avgPickupTime}\n\n` +
      `_Generated by ParkDrop Platform Admin_`;

    navigator.clipboard?.writeText(text);
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      {/* Header and Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-[#0F172A] tracking-tight">Reports</h1>
          <p className="text-xs text-[#475569] mt-0.5">
            Operational throughput, collection velocity, and cross-park performance benchmarks.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <ToggleGroup
            value={period}
            onValueChange={handlePeriodChange}
            options={periodOptions}
          />
          <button
            type="button"
            onClick={handleShareWhatsApp}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-[#E2E8F0] bg-white text-xs font-semibold text-[#0F172A] hover:bg-[#F8FAFC] transition-colors shadow-xs"
            title="Share summary on WhatsApp (excludes owed amounts)"
          >
            <Share2 className="w-3.5 h-3.5 text-emerald-600" />
            <span className="hidden sm:inline">Share WhatsApp</span>
          </button>
        </div>
      </div>

      {/* METRICS GRID — Spec §6.7: 3x2 or 2x3 cards, 24px/800 number, 13px label */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {/* Packages Received */}
        <div className="bg-white rounded-xl border border-[#E2E8F0] p-5 shadow-xs">
          <span className="text-[13px] font-medium text-[#475569]">Packages Received</span>
          <div className="text-[24px] font-extrabold text-[#0F172A] tabular-nums mt-1">
            {metrics?.received || 0}
          </div>
          <span className="text-[11px] text-[#94A3B8] block mt-0.5">Inbound intake</span>
        </div>

        {/* Packages Collected */}
        <div className="bg-white rounded-xl border border-[#E2E8F0] p-5 shadow-xs">
          <span className="text-[13px] font-medium text-[#475569]">Packages Collected</span>
          <div className="text-[24px] font-extrabold text-[#10B981] tabular-nums mt-1">
            {metrics?.collected || 0}
          </div>
          <span className="text-[11px] text-[#94A3B8] block mt-0.5">Customer pick-ups</span>
        </div>

        {/* Revenue Collected */}
        <div className="bg-white rounded-xl border border-[#E2E8F0] p-5 shadow-xs">
          <span className="text-[13px] font-medium text-[#475569]">Revenue Collected</span>
          <div className="text-[24px] font-extrabold text-[#0F172A] tabular-nums mt-1">
            {metrics?.revenueFormatted || '₦0.00'}
          </div>
          <span className="text-[11px] text-[#94A3B8] block mt-0.5">Excludes owed funds</span>
        </div>

        {/* Still Waiting */}
        <div className="bg-white rounded-xl border border-[#E2E8F0] p-5 shadow-xs">
          <span className="text-[13px] font-medium text-[#475569]">Still Waiting</span>
          <div className="text-[24px] font-extrabold text-[#2563EB] tabular-nums mt-1">
            {metrics?.waiting || 0}
          </div>
          <span className="text-[11px] text-[#94A3B8] block mt-0.5">Awaiting customer collection</span>
        </div>

        {/* Currently Overdue */}
        <div className={`rounded-xl border p-5 shadow-xs ${
          metrics?.overdue > 0 ? 'bg-[#FFFBEB] border-[#FDE68A]' : 'bg-white border-[#E2E8F0]'
        }`}>
          <span className={`text-[13px] font-medium ${metrics?.overdue > 0 ? 'text-[#92400E]' : 'text-[#475569]'}`}>
            Currently Overdue (&gt;24h)
          </span>
          <div className={`text-[24px] font-extrabold tabular-nums mt-1 ${
            metrics?.overdue > 0 ? 'text-[#B45309]' : 'text-[#0F172A]'
          }`}>
            {metrics?.overdue || 0}
          </div>
          <span className="text-[11px] text-[#94A3B8] block mt-0.5">Storage fee applicable</span>
        </div>

        {/* Average Pickup Time */}
        <div className="bg-white rounded-xl border border-[#E2E8F0] p-5 shadow-xs">
          <span className="text-[13px] font-medium text-[#475569]">Average Pickup Time</span>
          <div className="text-[24px] font-extrabold text-[#0F172A] tabular-nums mt-1">
            {metrics?.avgPickupTime || '—'}
          </div>
          <span className="text-[11px] text-[#94A3B8] block mt-0.5">Arrival to handover</span>
        </div>

        {/* Returned (only if > 0 per spec) */}
        {metrics?.returned > 0 && (
          <div className="bg-white rounded-xl border border-[#E2E8F0] p-5 shadow-xs">
            <span className="text-[13px] font-medium text-[#DC2626]">Returned to Sender</span>
            <div className="text-[24px] font-extrabold text-[#DC2626] tabular-nums mt-1">
              {metrics.returned}
            </div>
            <span className="text-[11px] text-[#94A3B8] block mt-0.5">Uncollected return</span>
          </div>
        )}

        {/* Cancelled (only if > 0 per spec) */}
        {metrics?.cancelled > 0 && (
          <div className="bg-white rounded-xl border border-[#E2E8F0] p-5 shadow-xs">
            <span className="text-[13px] font-medium text-[#64748B]">Cancelled Packages</span>
            <div className="text-[24px] font-extrabold text-[#64748B] tabular-nums mt-1">
              {metrics.cancelled}
            </div>
            <span className="text-[11px] text-[#94A3B8] block mt-0.5">Voided arrivals</span>
          </div>
        )}
      </div>

      {/* PACKAGES PER DAY CHART — Spec §6.7: Bar chart showing volume */}
      <div className="bg-white rounded-2xl border border-[#E2E8F0] p-6 shadow-xs">
        <div className="mb-6">
          <h2 className="text-base font-bold text-[#0F172A] tracking-tight">Packages Handled Per Day</h2>
          <p className="text-xs text-[#64748B] mt-0.5">
            Daily inbound package registrations vs completed collections
          </p>
        </div>

        <div className="h-[280px] w-full">
          {trendData && trendData.length > 0 ? (
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={trendData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#F1F5F9" />
                <XAxis
                  dataKey="date"
                  axisLine={false}
                  tickLine={false}
                  tick={{ fill: '#64748B', fontSize: 12, fontWeight: 500 }}
                />
                <YAxis
                  axisLine={false}
                  tickLine={false}
                  tick={{ fill: '#64748B', fontSize: 12 }}
                  allowDecimals={false}
                />
                <Tooltip
                  cursor={{ fill: '#F8FAFC' }}
                  content={({ active, payload, label }) => {
                    if (active && payload && payload.length) {
                      return (
                        <div className="bg-[#0F172A] text-white p-3 rounded-xl shadow-xl text-xs space-y-1">
                          <p className="font-bold text-[#94A3B8]">{label}</p>
                          <div className="flex items-center justify-between gap-4">
                            <span className="text-[#60A5FA]">Received:</span>
                            <span className="font-bold font-mono">{payload[0]?.value}</span>
                          </div>
                          <div className="flex items-center justify-between gap-4">
                            <span className="text-[#34D399]">Collected:</span>
                            <span className="font-bold font-mono">{payload[1]?.value}</span>
                          </div>
                        </div>
                      );
                    }
                    return null;
                  }}
                />
                <Legend verticalAlign="top" align="right" wrapperStyle={{ paddingBottom: '16px', fontSize: '12px' }} />
                <Bar name="Received" dataKey="received_count" fill="#2563EB" radius={[4, 4, 0, 0]} maxBarSize={36} />
                <Bar name="Collected" dataKey="collected_count" fill="#10B981" radius={[4, 4, 0, 0]} maxBarSize={36} />
              </BarChart>
            </ResponsiveContainer>
          ) : (
            <div className="h-full flex items-center justify-center text-xs text-[#94A3B8]">
              No activity data recorded in this period.
            </div>
          )}
        </div>
      </div>

      {/* PICKUP POINT COMPARISON TABLE — Spec §6.7 */}
      <div className="bg-white rounded-2xl border border-[#E2E8F0] p-6 shadow-xs">
        <div className="mb-4">
          <h2 className="text-base font-bold text-[#0F172A] tracking-tight">Pickup Point Benchmark Comparison</h2>
          <p className="text-xs text-[#64748B]">All registered locations ranked by intake volume</p>
        </div>

        <div className="overflow-hidden rounded-xl border border-[#E2E8F0]">
          <Table>
            <TableHeader className="bg-[#F8FAFC]">
              <TableRow>
                <TableHead className="font-semibold text-xs text-[#475569]">Pickup Point</TableHead>
                <TableHead className="font-semibold text-xs text-[#475569]">Park</TableHead>
                <TableHead className="font-semibold text-xs text-[#475569] text-center">Received</TableHead>
                <TableHead className="font-semibold text-xs text-[#475569] text-center">Collected</TableHead>
                <TableHead className="font-semibold text-xs text-[#475569] text-center">Collection Rate</TableHead>
                <TableHead className="font-semibold text-xs text-[#475569] text-right">Revenue (₦)</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {pickupPointComparison && pickupPointComparison.length > 0 ? (
                pickupPointComparison.map((biz) => (
                  <TableRow key={biz.id} className="hover:bg-[#F8FAFC]">
                    <TableCell className="font-semibold text-sm text-[#0F172A]">
                      {biz.name}
                    </TableCell>
                    <TableCell className="text-xs text-[#64748B]">
                      {biz.park}
                    </TableCell>
                    <TableCell className="text-center font-mono text-sm tabular-nums">
                      {biz.received > 0 ? biz.received : '—'}
                    </TableCell>
                    <TableCell className="text-center font-mono text-sm tabular-nums">
                      {biz.collected > 0 ? biz.collected : '—'}
                    </TableCell>
                    <TableCell className="text-center font-mono text-xs tabular-nums">
                      {biz.received > 0 ? `${biz.collectionRate}%` : '—'}
                    </TableCell>
                    <TableCell className="text-right font-mono font-bold text-sm text-emerald-700 tabular-nums">
                      {biz.revenue}
                    </TableCell>
                  </TableRow>
                ))
              ) : (
                <TableRow>
                  <TableCell colSpan={6} className="text-center py-8 text-xs text-[#94A3B8]">
                    No pickup points registered.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  );
}
